/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Prabath
 */
public class Login extends javax.swing.JFrame {

    int evtX ;
    int evtY ;
    int x;
    int y;
    Connection connection;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        connection = db_connection.DatabaseConnection.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pw_txt = new javax.swing.JTextField();
        un_txt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        forgot_pw = new javax.swing.JLabel();
        skip_btn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        login_btn = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pw_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pw_txt.setForeground(new java.awt.Color(143, 145, 154));
        pw_txt.setText("Enter Your Password...");
        pw_txt.setBorder(null);
        pw_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pw_txtMouseClicked(evt);
            }
        });
        jPanel1.add(pw_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 350, 200, 30));

        un_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        un_txt.setForeground(new java.awt.Color(143, 145, 154));
        un_txt.setText("Enter Your Username...");
        un_txt.setBorder(null);
        un_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                un_txtMouseClicked(evt);
            }
        });
        jPanel1.add(un_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 240, 200, 30));
        un_txt.getAccessibleContext().setAccessibleDescription("");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Group 20.png"))); // NOI18N
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(143, 145, 154));
        jLabel10.setText("analysis. ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel8.setText("Tool.");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 80, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(83, 109, 254));
        jLabel6.setText("Need to Register ?");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 586, -1, -1));

        forgot_pw.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        forgot_pw.setForeground(new java.awt.Color(83, 109, 254));
        forgot_pw.setText("Forgot Password ?");
        forgot_pw.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgot_pw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgot_pwMouseClicked(evt);
            }
        });
        jPanel1.add(forgot_pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 430, -1, -1));

        skip_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Group 7.png"))); // NOI18N
        skip_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        skip_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                skip_btnMouseClicked(evt);
            }
        });
        jPanel1.add(skip_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 420, -1, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Group 6.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, -1, -1));

        login_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Group 2.png"))); // NOI18N
        login_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_btnMouseClicked(evt);
            }
        });
        jPanel1.add(login_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, 410, 80));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Group 1.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 580, -1, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/undraw_in_progress_ql66.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, 360));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel9.setText("JAVA & C++ Complexity Measuring ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 50));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(143, 145, 154));
        jLabel11.setText("Measure the complexity of your codes with our    ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(143, 145, 154));
        jLabel12.setText("measuring tool through new dimensions of code");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Minus_20px.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1103, 5, 20, 20));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Delete_20px.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 5, 20, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pw_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pw_txtMouseClicked
       pw_txt.setText("");
    }//GEN-LAST:event_pw_txtMouseClicked

    private void un_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_un_txtMouseClicked
       un_txt.setText("");
    }//GEN-LAST:event_un_txtMouseClicked

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        x = evt.getXOnScreen();
        y = evt.getYOnScreen();
        
        this.setLocation(x-evtX, y-evtY);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        evtX = evt.getX();
        evtY = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        Register reg = new Register();
        reg.setVisible(true);
        reg.pack();
        reg.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void forgot_pwMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgot_pwMouseClicked

        String un = un_txt.getText();
        
        if(un.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Please type user name as u remember!");
        }else{
            try {
                String sql = "select * from users where user_name=?";
                PreparedStatement ps = (PreparedStatement)connection.prepareStatement(sql);
                ps.setString(1, un);
                ResultSet rs = (ResultSet)ps.executeQuery();
                if(rs.first()){
                    String answ1 = rs.getString("answer1");
                    String answ2 = rs.getString("answer2");
                    String answ3 = rs.getString("answer3");
                    String q1 = rs.getString("sec_ques1");
                    String q2 = rs.getString("sec_ques2");
                    String q3 = rs.getString("sec_ques3");
                    Register reg = new Register();
                    reg.setSecurityQuestions(un,answ1, answ2, answ3, q1, q2, q3);
                    reg.setVisible(true);
                    reg.pack();
                    reg.setLocationRelativeTo(null);
                    this.dispose();
                    
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Try Again!There is no username related to given!");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_forgot_pwMouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        LearnMore learnmore = new LearnMore();
        learnmore.setVisible(true);
        learnmore.pack();
        learnmore.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void skip_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_skip_btnMouseClicked
        Home home = new Home();
        home.setVisible(true);
        home.pack();
        home.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_skip_btnMouseClicked

    private void login_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btnMouseClicked
        
        String un = un_txt.getText().trim();
        String pw = pw_txt.getText().trim();
        
        if(!un.isEmpty() && !pw.isEmpty()){
            try {
                String sql = "select * from users where user_name=? and password=?";
                
                PreparedStatement ps = (PreparedStatement)connection.prepareStatement(sql);
                ps.setString(1, un);
                ps.setString(2, pw);
                
                ResultSet rs = (ResultSet)ps.executeQuery();
                if(rs.first()){
                    Home home = new Home();
                    home.setLogin(true);
                    home.setVisible(true);
                    home.pack();
                    home.setLocationRelativeTo(null);
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(rootPane, "There is no related account to given data!");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
    }//GEN-LAST:event_login_btnMouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        this.setState(1);
    }//GEN-LAST:event_jLabel14MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel forgot_pw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel login_btn;
    private javax.swing.JTextField pw_txt;
    private javax.swing.JLabel skip_btn;
    private javax.swing.JTextField un_txt;
    // End of variables declaration//GEN-END:variables

    public void registeredUserSet(String un, String pw){
        un_txt.setText(un);
        pw_txt.setText(pw);
    }
}
